/*
 * OMAP44xx and OMAP54xx PRCM MPU function prototypes
 *
 * Copyright (C) 2010, 2013 Texas Instruments, Inc.
 * Copyright (C) 2010 Nokia Corporation
 *
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#ifndef __LINUX_POWER_OMAP_PRCM_MPU_44XX_54XX_H
#define __LINUX_POWER_OMAP_PRCM_MPU_44XX_54XX_H

#ifndef __ASSEMBLER__
extern void __iomem *prcm_mpu_base;

void omap4_prcm_mpu_set_cpu_context_offset(u16 offset);
void omap4_prcm_mpu_clear_prev_cpu_logic_pwrst(unsigned int cpu_id);
void omap5_prcm_mpu_enable_mercury_retention_mode(void);
void __init omap2_set_globals_prcm_mpu(void __iomem *prcm_mpu);
#endif

#endif
