#
# TI Keystone SOC drivers
#
obj-$(CONFIG_KEYSTONE_NAVIGATOR_QMSS)	+= knav_qmss.o
knav_qmss-y := knav_qmss_queue.o knav_qmss_acc.o
obj-$(CONFIG_KEYSTONE_NAVIGATOR_DMA)	+= knav_dma.o
obj-$(CONFIG_WKUP_M3_IPC)		+= wkup_m3_ipc.o
obj-$(CONFIG_ARCH_OMAP2PLUS)		+= omap_pm_domains.o
