obj-y					+= prm_common.o
obj-$(CONFIG_ARCH_OMAP2)		+= prm2xxx.o
am33xx-43xx-prcm-common			+= prm33xx.o
obj-$(CONFIG_SOC_AM33XX)		+= $(am33xx-43xx-prcm-common)
obj-$(CONFIG_SOC_AM43XX)		+= $(am33xx-43xx-prcm-common)
obj-$(CONFIG_SOC_TI81XX)		+= $(am33xx-43xx-prcm-common)
