/*
 * OMAP4 Clock domains framework
 *
 * Copyright (C) 2009-2011 Texas Instruments, Inc.
 * Copyright (C) 2009-2011 Nokia Corporation
 *
 * Abhijit Pagare (abhijitpagare@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 * Paul Walmsley (paul@pwsan.com)
 *
 * This file is automatically generated from the OMAP hardware databases.
 * We respectfully ask that any modifications to this file be coordinated
 * with the public linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the autogeneration scripts are kept
 * up-to-date with the file contents.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/kernel.h>
#include <linux/io.h>
#include <linux/of.h>

#include "clockdomain.h"
#include "cm1_44xx.h"
#include "cm2_44xx.h"

#include "cm-regbits-44xx.h"
#include "prm44xx.h"
#include "prcm44xx.h"
#include "prcm_mpu44xx.h"

static struct clockdomain l4_cefuse_44xx_clkdm = {
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static struct clockdomain l4_cfg_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L4CFG_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP,
};

static struct clockdomain tesla_44xx_clkdm = {
	.dep_bit	  = OMAP4430_TESLA_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain l3_gfx_44xx_clkdm = {
	.dep_bit	  = OMAP4430_GFX_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain ivahd_44xx_clkdm = {
	.dep_bit	  = OMAP4430_IVAHD_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain l4_secure_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L4SEC_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain l4_per_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L4PER_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain abe_44xx_clkdm = {
	.dep_bit	  = OMAP4430_ABE_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain l3_instr_44xx_clkdm = {
};

static struct clockdomain l3_init_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L3INIT_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain d2d_44xx_clkdm = {
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static struct clockdomain mpu0_44xx_clkdm = {
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static struct clockdomain l3_emif_44xx_clkdm = {
	.dep_bit	  = OMAP4430_MEMIF_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static struct clockdomain l4_ao_44xx_clkdm = {
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static struct clockdomain ducati_44xx_clkdm = {
	.dep_bit	  = OMAP4430_DUCATI_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain mpu_44xx_clkdm = {
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static struct clockdomain l3_2_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L3_2_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP,
};

static struct clockdomain l3_1_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L3_1_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP,
};

static struct clockdomain iss_44xx_clkdm = {
	.flags		  = CLKDM_CAN_SWSUP,
};

static struct clockdomain l3_dss_44xx_clkdm = {
	.dep_bit	  = OMAP4430_DSS_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP_SWSUP,
};

static struct clockdomain l4_wkup_44xx_clkdm = {
	.dep_bit	  = OMAP4430_L4WKUP_STATDEP_SHIFT,
	.flags		  = CLKDM_CAN_HWSUP | CLKDM_ACTIVE_WITH_MPU,
};

static struct clockdomain emu_sys_44xx_clkdm = {
	.flags		  = (CLKDM_CAN_ENABLE_AUTO | CLKDM_CAN_FORCE_WAKEUP |
			     CLKDM_MISSING_IDLE_REPORTING),
};

static struct clockdomain l3_dma_44xx_clkdm = {
	.flags		  = CLKDM_CAN_FORCE_WAKEUP | CLKDM_CAN_HWSUP,
};

static const struct of_device_id omap_clkdm_match_table[] __initconst = {
	{ .compatible = "ti,omap4-mpu-clkdm", .data = &mpu0_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-1-clkdm", .data = &l3_1_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-2-clkdm", .data = &l3_2_44xx_clkdm },
	{ .compatible = "ti,omap4-l4-cfg-clkdm", .data = &l4_cfg_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-instr-clkdm",
	  .data = &l3_instr_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-emif-clkdm", .data = &l3_emif_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-dma-clkdm", .data = &l3_dma_44xx_clkdm },
	{ .compatible = "ti,omap4-ducati-clkdm", .data = &ducati_44xx_clkdm },
	{ .compatible = "ti,omap4-d2d-clkdm", .data = &d2d_44xx_clkdm },
	{ .compatible = "ti,omap4-l4-cefuse-clkdm",
	  .data = &l4_cefuse_44xx_clkdm },
	{ .compatible = "ti,omap4-tesla-clkdm", .data = &tesla_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-gfx-clkdm", .data = &l3_gfx_44xx_clkdm },
	{ .compatible = "ti,omap4-ivahd-clkdm", .data = &ivahd_44xx_clkdm },
	{ .compatible = "ti,omap4-l4-secure-clkdm",
	  .data = &l4_secure_44xx_clkdm },
	{ .compatible = "ti,omap4-l4-per-clkdm", .data = &l4_per_44xx_clkdm },
	{ .compatible = "ti,omap4-abe-clkdm", .data = &abe_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-init-clkdm", .data = &l3_init_44xx_clkdm },
	{ .compatible = "ti,omap4-l4-alwon-clkdm", .data = &l4_ao_44xx_clkdm },
	{ .compatible = "ti,omap4-mpuss-clkdm", .data = &mpu_44xx_clkdm },
	{ .compatible = "ti,omap4-iss-clkdm", .data = &iss_44xx_clkdm },
	{ .compatible = "ti,omap4-l3-dss-clkdm", .data = &l3_dss_44xx_clkdm },
	{ .compatible = "ti,omap4-l4-wkup-clkdm", .data = &l4_wkup_44xx_clkdm },
	{ .compatible = "ti,omap4-emu-sys-clkdm", .data = &emu_sys_44xx_clkdm },
	{ }
};

void __init omap44xx_clockdomains_init(void)
{
	clkdm_register_platform_funcs(&omap4_clkdm_operations);
	of_omap_clockdomain_init(omap_clkdm_match_table);
	clkdm_complete_init();
}
